# Generated by Django 4.1.3 on 2023-02-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisterStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("st_name", models.TextField(max_length=100)),
                ("st_contact", models.TextField(max_length=10)),
                ("st_email", models.TextField(max_length=50)),
                ("st_username", models.TextField(max_length=100)),
                ("st_password", models.TextField(max_length=100)),
                ("st_confirmpassword", models.TextField(max_length=100)),
                ("st_usertype", models.TextField(max_length=100)),
                ("st_status", models.TextField(max_length=100)),
            ],
        ),
    ]
